[package]
name = "ccid_tracker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
candid = "0.9.11"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
candid = "0.9.11"